### ISSUE TITLE
cv2.dnn.readNet  fail

### ISSUE THREAD

**Issue by Xuagent** [hpc203/yolov5-face-landmarks-opencv-v2#1]
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-1hg9yufe\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1410: error: (-2:Unspecified error) in function
'void __cdecl cv::dnn::dnn4_v20200609::ONNXImporter::populateNet(class cv::dnn::dnn4_v20200609::Net)'
>  (expected: 'shapes.depth() == CV_32S'), where
>     'shapes.depth()' is 5 (CV_32FC1)
> must be equal to
>     'CV_32S' is 4 (CV_32SC1)

What could be the reason for this? and how to fix it？
my opencv-python==4.4.0.40
Thanks

**Comment by hpc203** [comment]
> cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-1hg9yufe\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1410: error: (-2:Unspecified error) in function
> 'void __cdecl cv::dnn::dnn4_v20200609::ONNXImporter::populateNet(class cv::dnn::dnn4_v20200609::Net)'
> 
> > (expected: 'shapes.depth() == CV_32S'), where
> > 'shapes.depth()' is 5 (CV_32FC1)
> > must be equal to
> > 'CV_32S' is 4 (CV_32SC1)
> 
> What could be the reason for this? and how to fix it？
> my opencv-python==4.4.0.40
> Thanks

你是用的opencv版本低了，升级opencv到最新版本再运行程序试试

**Comment by Xuagent** [comment]
opencv-pyhton==4.5.2 
多谢，解决
