### ISSUE TITLE
大佬是否可以公开训练的项目

### ISSUE THREAD

**Issue by Dandelion111** [hpc203/yolov5-face-landmarks-opencv-v2#2]
大佬是否可以公开训练的项目

**Comment by hpc203** [comment]
https://github.com/deepcam-cn/yolov5-face

**Comment by hpc203** [comment]
> 大佬是否可以公开训练的项目

https://github.com/deepcam-cn/yolov5-face

**Comment by Dandelion111** [comment]
> > 大佬是否可以公开训练的项目
> 
> https://github.com/deepcam-cn/yolov5-face

感谢
